Blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<uuid:post_uuid>/', views.detail, name='detail'),
    path('<uuid:post_uuid>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('<str:label>', views.search, name='search'),
]

Simple_Django_Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Blog.urls')),
]

Blog/models.py
import uuid
from django.db import models
from django.utils import timezone
from datetime import timedelta


def set_k(val: int) -> str:
    if val >= 1000:
        return "{:.1f}k".format(val / 1000)
    else:
        return str(val)


class Post(models.Model):
    title = models.CharField('Названеие статьи',  max_length=220)
    body = models.TextField('Текст статьи', default='')
    date = models.DateTimeField('Дата и время статьи', default=timezone.now)
    view = models.PositiveIntegerField('Просмотры', default=0)
    uuid = models.UUIDField('uuid', default=uuid.uuid4, editable=False, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статью'
        verbose_name_plural = 'Статьи'

    def get_view(self):
        return set_k(self.view)

    def is_new(self):
        return self.date >= timezone.now() - timedelta(days=7)

    def len_comments(self):
        return len(Comment.objects.filter(post_id__uuid=self.uuid))


class Comment(models.Model):
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField('Автор', max_length=100)
    body = models.TextField('Текст комментария', default='')
    date = models.DateTimeField('Дата и время', default=timezone.now)

    def __str__(self):
        return self.author

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Tag(models.Model):
    tag_id = models.ManyToManyField(Post)
    tag_name = models.CharField('Метка', max_length=50, unique=True)

    def __str__(self):
        return self.tag_name

    class Meta:
        verbose_name = 'Метку'
        verbose_name_plural = 'Метки'

Blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Post, Tag, Comment


def init_with_tag() -> dict:
    return {'tags': Tag.objects.order_by('tag_name')}


def index(request):
    list_ = init_with_tag()
    posts = Post.objects.order_by('-date')
    paginator = Paginator(posts, 20)
    page = request.GET.get('page')
    try:
        post_page = paginator.page(page)
    except PageNotAnInteger:
        post_page = paginator.page(1)
    except EmptyPage:
        post_page = paginator.page(paginator.num_pages)
    list_.update({'post_list': post_page})
    return render(request, 'Blog/page.html', list_)


def detail(request, post_uuid):
    try:
        list_ = init_with_tag()
        uuid = Post.objects.get(uuid=post_uuid)
        uuid.view += 1
        uuid.save()
        list_.update({'uuid': uuid})
        list_.update({'comments': uuid.comment_set.order_by('-id')})
    except Exception:
        raise Http404('Статья не найдена!')
    return render(request, 'Blog/page-detail.html', list_)


def leave_comment(request, post_uuid):
    try:
        uuid = Post.objects.get(uuid=post_uuid)
    except Exception:
        raise Http404('Статья не найдена!')
    uuid.comment_set.create(author=request.POST['aname'], body=request.POST['atext'])
    return HttpResponseRedirect(reverse('blog:detail', args=(uuid.uuid, )))


def search(request, label):
    try:
        list_ = init_with_tag()
        if request.GET.get('q', ''):
            label = request.GET.get('q', '')
            posts = Post.objects.filter(title__contains=label).order_by('-date')
            if not posts:
                list_.update({'search_list': Post.objects.filter(body__contains=label).order_by('-date'), 'label': label})
            else:
                list_.update({'search_list': posts, 'label': label})
        else:
            list_.update({'search_list': Post.objects.filter(tag__tag_name__contains=label).order_by('-date'),
                          'label': label})
    except Exception:
        raise Http404('Статьи не найдены!')
    return render(request, 'Blog/search-page.html', list_)

templates/Blog/Wrapper.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Programmer's Blog {% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'Blog/css/template.css' %}" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Russo+One&display=swap" rel="stylesheet">

</head>
<body>
{% include 'Blog/right-panel.html' %}
{% include 'Blog/footer.html' %}

<div class="content">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

templates/Blog/footer.html
{% load static %}
<div class="footer_panel">
    <hr class="hr_footer">
    <div class="f_center">
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/google.png' %}" alt="google" title="Google+"></a></div>
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/youtube.png' %}" alt="youtube" title="Youtube"></a></div>
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/facebook.png' %}" alt="facebook" title="Facebook"></a></div>
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/instagram.png' %}" alt="instagram" title="Instagram"></a></div>
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/vk.png' %}" alt="vk" title="Вконтакте"></a></div>
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/linkedin.png' %}" alt="linkedin" title="LinkedIn"></a></div>
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/steam.png' %}" alt="steam" title="Steam"></a></div>
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/pinterest.png' %}" alt="pinterest" title="Pinterest"></a></div>
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/telegram.png' %}" alt="telegram" title="Telegram"></a></div>
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/whatsapp.png' %}" alt="whatsapp" title="Whatsapp"></a></div>
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/viber.png' %}" alt="viber" title="Viber"></a></div>
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/skype.png' %}" alt="skype" title="Skype"></a></div>
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/twitter.png' %}" alt="twitter" title="Twitter"></a></div>
    <div class="social-icon"><a href="#"><img src="{% static 'Blog/images/social/yandex.png' %}" alt="yandex" title="Yandex"></a></div>
    <div class="social-icon"><a href="https://github.com/JitteryMan/Simple-Django-Blog"><img src="{% static 'Blog/images/social/github.png' %}" alt="github" title="github"></a></div>
    <div class="social-icon"><a href="https://money.yandex.ru/to/41001565554113" target="_blank"><img src="{% static 'Blog/images/social/ya_money.png' %}" alt="yandex-money" title="Яндекс.Деньги"></a></div>
    </div>
</div>

templates/Blog/page-detail.html
{% extends 'Blog/Wrapper.html' %}

{% block title %}{{ uuid.title }}{% endblock %}

    {% block content %}
        <div class="post">
                <div class="date">
                        <div class="date_time">{{ uuid.date|date:"d.m" }}<br>{{ uuid.date|date:"Y" }}</div>
                        <div class="date-block views">{{ uuid.get_view }}</div>
                        <div class="date-block com">{{ uuid.len_comments }}</div>

                </div>
            <div class="post_det">
                <h1>{{ uuid.title }}</h1>
                <div style="text-align: justify">{{ uuid.body|safe|linebreaks }}
                </div>
            </div>
        </div>
        <div style="clear: both"></div>
        <hr>
        {% if comments %}
            <h2>Комментарии:</h2>
        <div>
            {% for com in comments %}
                <div class="post">
                    <div class="date">
                        <div class="date_time">
                            {{ com.date|date:"d.m" }}<br>{{ com.date|date:"Y" }}
                        </div>
                    </div>
                    <div class="post_det" style="min-height: 0">
                        <h3>{{ com.author }}</h3>
                        {{ com.body|linebreaks }}
                    </div>
                </div>
            {% endfor %}
        </div>
        {% else %}
            <div class="not-found" style="color: #777777">Комментариев нет</div>
        {% endif %}
        <hr>
        <h2>Оставить комментарий:</h2>
            <form action="{% url 'blog:leave_comment' uuid.uuid %}" method="post">
                {% csrf_token %}
                <input name="aname" required placeholder="Имя автора" type="text">
                <button type="submit">Оставить комментарий</button>
                <br>
                <textarea required placeholder="Текст сообщения..." name="atext" rows="5" cols="50" style="margin-bottom: 55px;"></textarea>
            </form>
    {% endblock %}

templates/Blog/page.html
{% extends 'Blog/Wrapper.html' %}

{% block title %} Блог программиста {% endblock %}

{% block content %}
    {% if post_list %}
        {% for pl in post_list %}

            <div class="post">
                <div class="date">
                    <div class="date_time">{{ pl.date|date:"d.m" }}<br>{{ pl.date|date:"Y" }}</div>
                    <div class="date-block views">{{ pl.get_view }}</div>
                    <div class="date-block com">{{ pl.len_comments }}</div>
                </div>
                <div class="post_det">
                    {% if pl.is_new %}
                        <div class="new-post">NEW</div>
                    {%  endif %}
                    <h1><a href="{% url 'blog:detail' pl.uuid %}"> {{ pl.title }}</a></h1>
                    <p>{{ pl.body|safe|linebreaks|truncatewords_html:15 }}</p>
                </div>
            </div>
        {% endfor %}

        <div class="pagination">
            <span class="step-links">
                {% if post_list.has_previous %}
                    <a href="?page={{ post_list.previous_page_number }}">Предыдущая</a>
                {% endif %}

                <span class="current">
                    Страница {{ post_list.number }} из {{ post_list.paginator.num_pages }}.
                </span>

                {% if post_list.has_next %}
                    <a href="?page={{ post_list.next_page_number }}">Следующая</a>
                {% endif %}
            </span>
        </div>

    {% else %}
        <div class="not-found">Статьи не найдены</div>
    {% endif %}
{% endblock %}

templates/Blog/right-panel.html
<div class="s_panel">
    <div class="logo">
        {% load static %}
        <a href="/"><img src="{% static "Blog/images/Logo.png" %}" alt="Блог программиста" title="Блог программиста"></a>
        <h2>БЛОГ ПРОГРАММИСТА</h2>
    </div>
    <div>
        {% if tags %}
            <ul class="menu">
            {% for tag in tags %}
                <li><a href="{% url "blog:search" tag.tag_name|lower %}">{{ tag.tag_name|upper }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>Метки не найдены</p>
        {% endif %}
    <div>
        <form action="{% url 'blog:search' 'search=' %}" method="get" >
            <input type="text" placeholder="Поиск..." name="q">
            <input type="submit" name="p" value="">
        </form>
    </div>
    </div>

</div>

templates/Blog/search-page.html
{% extends 'Blog/Wrapper.html' %}

{% block title %}Поиск: {% url 'blog:search' label %}{% endblock %}

{% block content %}
    {% if search_list %}
        {% for pl in search_list %}

            <div class="post">
                <div class="date">
                    <div class="date_time">{{ pl.date|date:"d.m" }}<br>{{ pl.date|date:"Y" }}</div>
                    <div class="date-block views">{{ pl.get_view }}</div>
                    <div class="date-block com">{{ pl.len_comments }}</div>
                </div>
                <div class="post_det">
                    {% if pl.is_new %}
                        <div class="new-post">NEW</div>
                    {%  endif %}
                    <h1><a href="{% url 'blog:detail' pl.uuid %}"> {{ pl.title }}</a></h1>
                    <p>{{ pl.body|safe|linebreaks|truncatewords_html:15 }}</p>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="not-found">Статьи не найдены</div>
    {% endif %}
{% endblock %}